spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/books-52
    username: postgres
    password: aks124alv124
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

